[project]
name = "recipe-lib"
version = "0.1.0"
description = "A recipe management application"
authors = ["Christoph Franzke"]
readme = "README.md"
license = "MIT"
dependencies = [
    fastapi
    uvicorn
    sqlalchemy
    psycopg2-binary
    jinja2
    requests
    beautifulsoup4
    python-jose[cryptography]
    bcrypt
    python-multipart
    python-dotenv
    alembic
    google-genai
    cloudinary
]