"""Add notes, times, rating, cook dates and frequency

Revision ID: 3091295c4570
Revises: ff41a4fdd454
Create Date: 2025-12-23 20:46:08.890930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3091295c4570'
down_revision: Union[str, Sequence[str], None] = 'ff41a4fdd454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('original_url', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('prep_time', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('cook_time', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('total_time', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('yields', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('cook_count', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('last_cooked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'last_cooked')
    op.drop_column('recipes', 'cook_count')
    op.drop_column('recipes', 'rating')
    op.drop_column('recipes', 'notes')
    op.drop_column('recipes', 'yields')
    op.drop_column('recipes', 'total_time')
    op.drop_column('recipes', 'cook_time')
    op.drop_column('recipes', 'prep_time')
    op.drop_column('recipes', 'original_url')
    # ### end Alembic commands ###
