"""add cooklist and date

Revision ID: 43f965bb99ff
Revises: be6891584c55
Create Date: 2026-01-22 13:00:56.785659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f965bb99ff'
down_revision: Union[str, Sequence[str], None] = 'be6891584c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('in_cooklist', sa.Boolean(), nullable=True))
    op.add_column('recipes', sa.Column('added_to_cooklist_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'added_to_cooklist_at')
    op.drop_column('recipes', 'in_cooklist')
    # ### end Alembic commands ###
