"""add users and recipe owner

Revision ID: 612bc5b6f8fe
Revises: 
Create Date: 2025-12-19 14:42:33.843743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612bc5b6f8fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('public_id', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recipes_public_id'), 'recipes', ['public_id'], unique=True)
    op.create_foreign_key(None, 'recipes', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_index(op.f('ix_recipes_public_id'), table_name='recipes')
    op.drop_column('recipes', 'owner_id')
    op.drop_column('recipes', 'public_id')
    # ### end Alembic commands ###
