"""add cookbooks and relationships

Revision ID: ff41a4fdd454
Revises: 612bc5b6f8fe
Create Date: 2025-12-21 12:58:13.056334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff41a4fdd454'
down_revision: Union[str, Sequence[str], None] = '612bc5b6f8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cookbooks_id'), 'cookbooks', ['id'], unique=False)
    op.create_index(op.f('ix_cookbooks_name'), 'cookbooks', ['name'], unique=False)
    op.create_table('cookbook_recipe',
    sa.Column('cookbook_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cookbook_id'], ['cookbooks.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('cookbook_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookbook_recipe')
    op.drop_index(op.f('ix_cookbooks_name'), table_name='cookbooks')
    op.drop_index(op.f('ix_cookbooks_id'), table_name='cookbooks')
    op.drop_table('cookbooks')
    # ### end Alembic commands ###
